apiVersion: janus.io/v1
kind: GatewayProxy
metadata:
  labels:
    app.kubernetes.io/name: janus-ingress-controller
    app.kubernetes.io/managed-by: kustomize
  name: gatewayproxy-sample
spec:
  # TODO(user): Add fields here
